CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER CONSTRAINT PK_Id_Cliente PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    APELLIDO VARCHAR2(20),
    EDAD NUMBER,
    BANNEADO NUMBER(1),
    USUARIO VARCHAR2(20),
    PASSW VARCHAR2(30),
    ESADMIN NUMBER(1)
);

CREATE TABLE METODOPAGO(
    METPAGO VARCHAR2(20) CONSTRAINT PK_METPAGO PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    DETALLES_PAGO VARCHAR2(30)
);

CREATE TABLE FACTURA(
    ID_FACTURA VARCHAR2(20) CONSTRAINT PK_Id_Factura PRIMARY KEY,
    ID_CLIENTE NUMBER(20) CONSTRAINT FK_Id_Cliente REFERENCES CLIENTE(ID_CLIENTE),
    METPAGO VARCHAR2(20) CONSTRAINT FK_Metodopago REFERENCES METODOPAGO(METPAGO),
    FECHA DATE
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO VARCHAR2(20) CONSTRAINT PK_Id_Producto PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    PRECIO NUMBER,
    STOCK NUMBER,
    DESCUENTO NUMBER
);

CREATE TABLE DETALLES_PEDIDO(
    ID_DETALLES VARCHAR2(20) CONSTRAINT PK_Id_Detalles_Producto PRIMARY KEY,
    ID_FACTURA VARCHAR2(20) CONSTRAINT FK_Id_Factura REFERENCES FACTURA(ID_FACTURA),
    ID_PRODUCTO VARCHAR2(20) CONSTRAINT FK_Id_Producto REFERENCES PRODUCTO(ID_PRODUCTO),
    CANTIDAD NUMBER,
    PRECIO NUMBER
);